### ISSUE TITLE
Heroku failed to bind to port in 60 seconds

### ISSUE THREAD

**Issue by curiousblueprints** [mickeymond/fusion-auth-heroku#1]
Reproduction steps:

- Click deploy to heroku button and confirm deployment
- Start the web process
- Observe the following error in the heroku logs after 60 seconds: 

`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`

**Comment by mickeymond** [comment]
@curiousblueprints That is a very nasty error I have not been able to figure out. It is an env issue but I do not know how to make it go away at the moment.
I was trying to replicate what the Hasura guys have done for Heroku deployments.
Feel free to contribute.

**Comment by curiousblueprints** [comment]
@mickeymond Heroku wants the port to be specified by env variable - I'm not sure if that is possible to specify when running the app https://fusionauth.io/docs/v1/tech/installation-guide/fusionauth-app/#start-fusionauth-app

**Comment by yarism** [comment]
Any updates on how to do to solve this?

**Comment by whereisanzi** [comment]
@yarism I used this in my Dockerfile and works fine

```Dockerfile
FROM fusionauth/fusionauth-app:latest

ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"

ENV FUSIONAUTH_APP_MEMORY="512M"

CMD export FUSIONAUTH_HTTP_PORT=$PORT && /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh run
```

**Comment by mickeymond** [comment]
Nice work @anzileiro
I have however made some updates to the Heroku Deploy Button at https://github.com/mickeymond/fusion-auth-heroku which you can follow from the issue https://github.com/mickeymond/fusion-auth-heroku/issues/2
Happy to hear your thoughts after testing it.
Pardon my long absence.

**Comment by mickeymond** [comment]
> Any updates on how to do to solve this?

Nice work @anzileiro
I have however made some updates to the Heroku Deploy Button at https://github.com/mickeymond/fusion-auth-heroku which you can follow from the issue #2
Happy to hear your thoughts after testing it.
Pardon my long absence.
