### ISSUE TITLE
Heroku memory quota exceeded

### ISSUE THREAD

**Issue by joeycs** [mickeymond/fusion-auth-heroku#2]
Reproduction steps:

1. Click "Deploy to Heroku" button to create new Heroku app for FusionAuth hosting
2. Make request to newly created app's domain (e.g. `my-fusionauth-app.herokuapp.com/login`)
3. Observe the following error in the app's logs after being redirected to maintenance mode (e.g. `my-fusionauth-app.herokuapp.com/maintenance-mode-database-configuration`):

```
Process running mem=524M(102.5%)
Error R14 (Memory quota exceeded)
```

I understand that you can upgrade a Heroku dyno to allot more than 512M of memory to it, but I'm not prepared to spend the minimum of $50 a month to do so. Has anyone been able to successfully deploy FusionAuth to Heroku on a free-tier dyno? If so, how?

**Comment by mickeymond** [comment]
@joeycs This is a Heroku Free Dyno limitation but the App should run probably slowly.
Also thanks a lot @joeycs I cherry-picked your commit at joeycs/fusion-auth-heroku@c320c9513224c45591332ec85d78989e136b54a5 into my repo and added the database env to be configured during the Heroku deployment. this allows you to come in with your external database and also maintain the same database whiles deploying new versions of the fusion-auth docker image.

**Comment by mickeymond** [comment]
@joeycs If you are able to set reachable DB properties as depicted below it should help you skip the maintenance-mode-database-configuration on future runs which seems to happen earlier whenever the Heroku free dyno wakes up from sleep.
![image](https://user-images.githubusercontent.com/33749130/139919715-3e5a8784-3e39-44ff-ab31-b59b363f2c0f.png)

**Comment by mickeymond** [comment]
@joeycs Please test out the new button so we can close this issue. Forgive my delays in getting back to you on time.

**Comment by mickeymond** [comment]
> @joeycs If you are able to set reachable DB properties as depicted below it should help you skip the maintenance-mode-database-configuration on future runs which seems to happen earlier whenever the Heroku free dyno wakes up from sleep. ![image](https://user-images.githubusercontent.com/33749130/139919715-3e5a8784-3e39-44ff-ab31-b59b363f2c0f.png)

Elephant SQL can get you a free hosted PostgreSQL for testing https://customer.elephantsql.com/instance
